import { RootContext } from "@/contexts";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { useLanguage, useLocale } from "./dictionaries";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const dict = await useLanguage();
  const locale = await useLocale();

  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:ndo-border-dark relative text-base text-gray-900 dark:bg-black dark:text-white`}
      >
        <RootContext dict={dict} locale={locale}>
          {children}
        </RootContext>
      </body>
    </html>
  );
}
